sudo: required

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-286246934562
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
